{{/*
ConfigMap for generating a tomcat-users.xml including all users and roles
*/}}
{{- with .Values.application.security.http.localUsers -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frank-console.fullname" $ }}-local-users
  labels:
    {{- include "frank-console.labels" $ | nindent 4 }}
data:
  localUsers.yml: |-
    users:
      {{- toYaml . | nindent 6 -}}
{{- end -}}
