apiVersion: v1
kind: Service
{{ template "frank-console.metadata" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "frank-console.selectorLabels" . | nindent 4 }}