## @section Frank!Framework parameters
## @descriptionStart
## This chart is a wrapper for the Frank!Framework chart.
## See the documentation for the Frank!Framework chart for more information.
## @descriptionEnd

frankframework:
  ## @param frankframework.image.registry frank2example image registry
  ## @param frankframework.image.repository frank2example image repository
  ## @param frankframework.image.tag frank2example image tag (immutable tags are recommended)
  ## @param frankframework.image.pullPolicy frank2example image pull policy
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  ## @param frankframework.image.pullSecrets frank2example image pull secrets
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - name: myRegistryKeySecretName
  ##
  image:
    registry: nexus.frankframework.org
    repository: frank2example
    tag: "latest"
    pullPolicy: IfNotPresent
    pullSecrets: []

  ## @param frankframework.application.dtap.stage Set the `DTAP` stage. Options: `LOC`, `DEV`, `TST`, `ACC`, `PRD`
  ## @param frankframework.application.resources [object] Set Yaml properties for configuring the connections for theFrank!Framework
  ## @extra frankframework.application.resources Note: If kept empty no resources.yml will be generated, this can be used if the application already has a resources.yml
  ## @extra frankframework.application.resources Note: Not all options will be documented here, please refer to the Frank!Framework documentation for more information.
  ## Example ref: https://github.com/frankframework/frankframework/blob/master/core/src/test/resources/resources.yml
  ## Implementation ref: https://github.com/frankframework/frankframework/blob/master/core/src/main/java/org/frankframework/jdbc/datasource/FrankResources.java
  ##
  application:
    dtap:
      stage: LOC
    resources:
      jdbc:
        - name: frank2example
          type: org.h2.jdbcx.JdbcDataSource
          url: jdbc:h2:mem:frank2example;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;

  ## @param frankframework.replicaCount Number of Frank!Framework replicas to deploy
  ##
  replicaCount: 1

  ## @param frankframework.securityContext.readOnlyRootFilesystem Set the security context for the Frank!Framework containers
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ##
  securityContext:
    readOnlyRootFilesystem: true
