{{/*
ConfigMap for configuring the Hazelcast network
*/}}
{{- if .Values.console.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hazelcast-network
  labels:
    {{- include "frankframework.labels" . | nindent 4 }}
data:
  hazelcast-network.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xmlns="http://www.hazelcast.com/schema/config">
        <network>
            <port auto-increment="false">5701</port>
            <join>
                <auto-detection enabled="false"/>
                <multicast enabled="false"/>
                <kubernetes enabled="true">
                    <service-dns>
                        {{ .Release.Name }}-hazelcast.{{ .Release.Namespace }}.svc.cluster.local
                    </service-dns>
                </kubernetes>
            </join>
        </network>
    </hazelcast>
    {{- end -}}