{{/*
ConfigMap for generating a ldap-role-mapping.properties
*/}}
{{- define "ff-common.configmap.k8s-specifics.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ff-common.fullname" . }}-k8s-specifics
  labels:
    {{- include "ff-common.labels" . | nindent 4 }}
data:
  K8sSpecifics.yaml: |-
    {{ toYaml .Values.frank.properties | nindent 4 }}
{{- end -}}
{{- define "ff-common.configmap.k8s-specifics" -}}
{{- template "ff-common.util.merge" (append . "ff-common.configmap.k8s-specifics.tpl") -}}
{{- end -}}
