{{- define "ff-common.secret.tpl" -}}
apiVersion: v1
kind: Secret
{{ template "ff-common.metadata" . }}
type: Opaque
data: {}
{{- end -}}
{{- define "ff-common.secret" -}}
{{- template "ff-common.util.merge" (append . "ff-common.secret.tpl") -}}
{{- end -}}
