{{/*
Create a ServiceAccount
*/}}
{{- define "ff-common.serviceAccount.tpl" -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ff-common.serviceAccountName" . }}
  labels:
    {{- include "ff-common.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
{{- define "ff-common.serviceAccount" -}}
{{- template "ff-common.util.merge" (append . "ff-common.serviceAccount.tpl") -}}
{{- end -}}
