{{/*
Copy of ff-common.configmap.context with h2 added
*/}}
{{- template "ff-common.configmap.context" (list . "frank2example.configmap.context" ) -}}
{{- define "frank2example.configmap.context" -}}
apiVersion: v1
kind: ConfigMap
data:
  context.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <Context>
        <JarScanner scanClassPath="false" scanAllFiles="false" scanAllDirectories="false"/>
      {{- with .Values.connections }}
        {{- range .jdbc }}
        {{- if eq .type "h2" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            factory="org.apache.naming.factory.BeanFactory"
            type="org.h2.jdbcx.JdbcDataSource"
            URL="jdbc:h2:{{ .host | default "mem" }}:{{ .database | default (include "ff-common.instance.name" $) }};NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;"
        />
        {{- end }}
        {{- if eq .type "oracle" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            factory="org.apache.naming.factory.BeanFactory"
            type="oracle.jdbc.xa.client.OracleXADataSource"
            URL="jdbc:oracle:thin:@{{ .host }}:{{ .port | default 1521}}:{{ .database | default (include "ff-common.instance.name" $) }}"
            user="{{ .username }}"
            password="{{ .password }}"
        />
          {{- end }}
          {{- if eq .type "mssql" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            auth="Container"
            factory="org.apache.naming.factory.BeanFactory"
            type="com.microsoft.sqlserver.jdbc.SQLServerXADataSource"
            URL="jdbc:sqlserver://{{ .host }}:{{ .port | default 1433}};database={{ .database | default (include "ff-common.instance.name" $) }}"
            user="{{ .username }}"
            password="{{ .password }}"
            sendStringParametersAsUnicode="false"
            sendTimeAsDatetime="true"
            selectMethod="direct"
            responseBuffering="adaptive"
            packetSize="4096"
            loginTimeout="10"
            lockTimeout="2000"
            lastUpdateCount="false"
            encrypt="{{ .ssl | default false}}"
            disableStatementPooling="true"
            applicationName="{{ (include "ff-common.instance.name" $) }}"
            applicationIntent="readwrite"
        />
          {{- end }}
          {{- if eq .type "mysql" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            factory="org.apache.naming.factory.BeanFactory"
            type="com.mysql.cj.jdbc.MysqlXADataSource"
            URL="jdbc:mysql://{{ .host }}:{{ .port | default 3306}}/{{ .database | default (include "ff-common.instance.name" $) }}"
            user="{{ .username }}"
            password="{{ .password }}"
            sslMode="{{ ternary "ENABLED" "DISABLED" (.ssl | default false)}}"
            serverTimezone="{{ $.Values.timeZone }}"
            allowPublicKeyRetrieval="true"
            pinGlobalTxToPhysicalConnection="true"
            socketTimeout="5000"
        />
          {{- end }}
          {{- if eq .type "mariadb" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            factory="org.apache.naming.factory.BeanFactory"
            type="com.mysql.cj.jdbc.MysqlXADataSource"
            URL="jdbc:mysql://{{ .host }}:{{ .port | default 3306}}/{{ .database | default (include "ff-common.instance.name" $) }}"
            user="{{ .username }}"
            password="{{ .password }}"
            sslMode="{{ ternary "ENABLED" "DISABLED" (.ssl | default false)}}"
            serverTimezone="{{ $.Values.timeZone }}"
            allowPublicKeyRetrieval="true"
            pinGlobalTxToPhysicalConnection="true"
            socketTimeout="5000"
        />
          {{- end }}
          {{- if eq .type "postgresql" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            factory="org.apache.naming.factory.BeanFactory"
            type="org.postgresql.xa.PGXADataSource"
            URL="jdbc:postgresql://{{ .host }}:{{ .port | default 5432}}/{{ .database | default (include "ff-common.instance.name" $) }}"
            user="{{ .username }}"
            password="{{ .password }}"
            sslMode="{{ ternary "REQUIRE" "DISABLE" (.ssl | default false)}}"
        />
          {{- end }}
          {{- if eq .type "db2" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            auth="Container"
            factory="org.apache.naming.factory.BeanFactory"
            type="com.ibm.db2.jcc.DB2XADataSource"
            serverName="{{ .host }}"
            portNumber="{{ .port | default 50000 }}"
            databaseName="{{ .database | default (include "ff-common.instance.name" $) }}"
            driverType="4"
            user="{{ .username }}"
            password="{{ .password }}"
        />
          {{- end }}
          {{- if eq .type "mongodb" }}
        <Resource
            name="{{ .name | default (printf "jdbc/%s" (include "ff-common.instance.name" $)) | lower }}"
            type="com.mongodb.MongoClient"
            factory="com.mongodb.client.MongoClientFactory"
            connectionString="mongodb://{{ .username }}:{{ .password }}@{{ .host }}"
            auth="Container"
            singleton="true"
        />
          {{- end }}
        {{- end }}
        {{- range .jms }}
          {{- if eq .type "activemq" }}
        <Resource
            name="{{ .name | default (printf "jms/%s" (include "ff-common.instance.name" $)) | lower }}"
            factory="org.apache.naming.factory.BeanFactory"
            type="org.apache.activemq.ActiveMQXAConnectionFactory"
            brokerURL="tcp://{{ .host }}:{{ .port | default 61616 }}?jms.xaAckMode=1"
        />
          {{- end }}
          {{- if eq .type "artemis" }}
        <Resource
            name="{{ .name | default (printf "jms/%s" (include "ff-common.instance.name" $)) | lower }}"
            factory="org.apache.naming.factory.BeanFactory"
            type="org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory"
            brokerURL="tcp://{{ .host }}:{{ .port | default 61616 }}"
        />
          {{- end }}
        {{- end }}
      {{- end }}
    </Context>
{{- end -}}
